### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by centralhardware** [aigarius/firefly3_telegram_oneshot#1]
```
2024-01-08T07:05:53.119116608Z Traceback (most recent call last):
   File "/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
     return complexjson.loads(self.text, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
     return _default_decoder.decode(s)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/firefly_oneshot_bot.py", line 285, in <module>
     main()
   File "/firefly_oneshot_bot.py", line 251, in main
     args["account_id"] = _find_account_id(args["account_name"])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/firefly_oneshot_bot.py", line 100, in _find_account_id
     t = _get_data_from_request("accounts/?type=asset")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/firefly_oneshot_bot.py", line 85, in _get_data_from_request
     data = r.json()
            ^^^^^^^^
   File "/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by aigarius** [comment]
It looks like it can not find a source asset account with the name you specified in the FIREFLY_SOURCE_ACCOUNT variable. This is also the first place that Firefly is being contacted so it could also be that the URL is wrong or the access token is incorrect.
If you add a line like `print(r.text)` or `print(r)` before line 85, then this should give you more info about the specific failure
